BuildMyUnicorn/Controllers/FinancialProjectionController.cs
using Business_Model.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BuildMyUnicorn.Business_Layer;

namespace BuildMyUnicorn.Controllers
{
    public class FinancialProjectionController : WebController
    {
        // GET: FinancialProjection
        public ActionResult Index()
        {
       
            return View();
        }

        public ActionResult GetFinancialProjection()
        {
            IEnumerable<FinancialProjection> ModelList = new FinanceManager().GetFinanceProjection();
            return PartialView("_FinancialProjectionPartial", ModelList);
        }

        public ActionResult AddFinancialProjection(FinancialProjection Model)
        {
            Model.ProjectionID = Guid.NewGuid();
            string result = new FinanceManager().AddFinanceProjection(Model);
            IEnumerable<FinancialProjection> ModelList = new FinanceManager().GetFinanceProjection();
            return PartialView("_FinancialProjectionPartial", ModelList);

        }

      
    }
}

BuildMyUnicorn/Views/FinancialProjection/Index.cshtml
@section PageStyle
{
    <link rel="stylesheet" type="text/css" href="~/assets/node_modules/datatables.net-bs4/css/dataTables.bootstrap4.css">
    <link rel="stylesheet" type="text/css" href="~/assets/node_modules/datatables.net-bs4/css/responsive.dataTables.min.css">

    <style>
        tr.jsRapidEntry {
            box-shadow: 0 5px 8px 0 rgba(50, 50, 50, 0.35);
            -webkit-box-shadow: 0 5px 8px 0 rgba(50, 50, 50, 0.35);
            -moz-box-shadow: 0 5px 8px 0 rgba(50, 50, 50, 0.35);
        }
        /*.table td, .table th {
            padding: 0rem !important;
            text-align:center;
            max-width:400px;
        }*/
    </style>
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Financial Projection</h4>
                <div id="education_fields"></div>
                <div class="row text-center">
              
                        <div class="col-md-1 nopadding">
                            <label>Year</label>
                            <div class="form-group">
                                <select id="Year" class="select2 form-control custom-select" style="width: 100%; height:36px;">

                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                    <option value="6">6</option>


                                </select>
                            </div>
                        </div>
                        <div class="col-md-1 nopadding">
                            <label>Month</label>
                            <div class="form-group">
                                <select id="Month" class="select2 form-control custom-select" style="width: 100%; height:36px;">
                                    
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                    <option value="6">6</option>
                                    <option value="7">7</option>
                                    <option value="8">8</option>
                                    <option value="9">9</option>
                                    <option value="10">10</option>
                                    <option value="11">11</option>
                                    <option value="12">12</option>


                                </select>
                            </div>
                        </div>

                        <div class="col-sm-2 nopadding">
                            <label>Activity</label>
                            <div class="form-group">
                                <select id="Activity" class="select2 form-control custom-select" style="width: 100%; height:36px;">
                                    <option>Select</option>
                                    <optgroup label="Customers">
                                        <option value="1">General licence</option>
                                        <option value="2">Student Licence</option>
                                        <option value="3">Affiliate</option>
                                        <option value="4">Consultancy Services  (hours)</option>
                                    </optgroup>

                                </select>
                            </div>
                        </div>

                        <div class="col-md-1 nopadding">
                            <label>Units</label>
                            <div class="form-group">
                                <input type="text" class="form-control  progress-required " id="Units">
                            </div>
                        </div>

                        <div class="col-md-1 nopadding">
                            <label>Charged</label>
                            <div class="form-group">
                                <input type="text" class="form-control  progress-required " id="Charged">
                            </div>
                        </div>



                        <div class="col-md-1 nopadding">
                            <label>Revenue </label>
                            <div class="form-group">
                                <input type="text" class="form-control  progress-required " id="Revenue" disabled>
                            </div>
                        </div>

                        <div class="col-md-3 nopadding">
                           
                            <div class="row"> 
                                <div class="col-md-6">
                                    <label>Increment</label>
                                    <div class="form-group">
                                        <input type="text" class="form-control  progress-required " id="Increment">


                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <label>Carry Forward</label>
                                    <div class="form-group">
                                        <div class="custom-control custom-checkbox" style="padding-top:8px">
                                            <input type="checkbox" class="custom-control-input" id="CarryForward" name="CarryForward" checked="checked">
                                            <label class="custom-control-label" for="CarryForward"></label>
                                        </div>

                                    </div>

                                </div>
                            </div>
                           

                        </div>

                        <div class="col-sm-2 nopadding">
                            <label></label>
                            <div class="form-group" style="padding-top:6px">
                                <button type="button" class="btn btn-success mr-2 jsAdd">Add</button> | X @*<i class="mdi mdi-close"></i>*@
                            </div>

                        </div>
                    </div>
                </div>
        </div>
    </div>
</div>
<div class="row jsFinancialProjectionContainer">
    @Html.Action("GetFinancialProjection", "FinancialProjection")
</div>


    @section PageScript
{
        <!-- This is data table -->
        <script src="~/assets/node_modules/datatables.net/js/jquery.dataTables.min.js"></script>
        <script src="~/assets/node_modules/datatables.net-bs4/js/dataTables.responsive.min.js"></script>
        <!-- start - This is for export functionality only -->
        <script src="https://cdn.datatables.net/buttons/1.5.1/js/dataTables.buttons.min.js"></script>
        <script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.flash.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
        <script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.html5.min.js"></script>
        <script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.print.min.js"></script>
        <!-- end - This is for export functionality only -->
        <script>
            $(".jsAdd").click(function (e) {
                e.preventDefault();
                var Model = {
                    "Year": $.trim($("#Year").val()),
                    "Month": $.trim($("#Month").val()),
                    "ActivityID": $.trim($("#Activity").val()),
                    "Units": $.trim($("#Units").val()),
                    "Increment": $.trim($("#Increment").val()),
                    "Charged": $.trim($("#Charged").val()),
                    "Revenue": $.trim($("#Revenue").val()),
                    "CarryForward": $("#CarryForward").is(':checked') ? true : false
                };
                console.log(Model);


                $.ajax({
                    url: GetBaseURL() + "FinancialProjection/AddFinancialProjection",
                    type: "POST",
                    data: JSON.stringify({ Model: Model }),
                    contentType: "application/json",
                    dataType: 'html',
                    error: function (data) {
                        alert(data);
                     
                    },
                    success: function (data) {
                        $(".jsFinancialProjectionContainer").html(data);
                    }
                });
            });

            $(document).on("blur", "#Units, #Charged ", function () {
                var Revenue = parseFloat($("#Units").val()) * parseFloat($("#Charged").val());
                if (isNaN(Revenue)) Revenue = 0;
                $("#Revenue").val(Revenue);

            });
            $(document).on("click", ".jsRevenue", function (e) {
                e.preventDefault();
                $(".jsRevenueContainer").toggle(10);
                //  $(".jsRevenueContainer").removeClass("hide");

            });
        </script>

    }